apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-java

  template:
    metadata:
      labels:
        app: hello-java

    spec:
      containers:
      - name: hello-java
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: {{ .Values.containerPort }}
